#!/bin/sh

# Copyright (C) 2021 Jak.W https://github.com/jakwings/surpass
#
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

set -e -u -f +x; unset -v _ IFS; export LC_ALL=C

SURPASS="${SURPASS-"$(command -v surpass)"}"
. "${SURPASS}"

opt_parse migrate 'key|force' ${1+"$@"}

job_init

PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR-"${HOME}/.password-store"}"

surpass_yesno "Start migrating passwords from \"${PASSWORD_STORE_DIR}\"?" \
  || surpass_bye 'Action aborted.'

surpass_echo "Migrating..." >&2

tmpnam="migrate.$$"
tmpdir="${SURPASS_STORE}/${tmpnam}"
job_push 'remove_all -f "${tmpdir}"'
create_dir "${tmpdir}"

cmd_bfs() {
  if ! case_in "${FILE}" '*.gpg'; then
    return 0
  fi

  passname1="${SUBPATH%.gpg}"
  passname2="${passname1}"

  if is_dir "${PASSWORD_STORE_DIR}/${passname1}"; then
    passname2="${passname2}_"
  fi
  while exists "${SURPASS_STORE}/${passname2}"; do
    passname2="${passname2}_"
  done
  if ! (check_passname passname "${passname2}" >/dev/null); then
    surpass_ekho "could not transform \"${passname1}\" to a valid passname"
    return 0
  else
    if [ x"${passname1}" != x"${passname2}" ]; then
      surpass_echo "Renamed \"${passname1}\" to \"${passname2}\""
    fi
  fi

  unset -v password  # unexport
  password="$(LC_ALL='' pass show "${passname1}")"

  echo "${password}" | surpass_edit "${tmpnam}/${passname2}" >/dev/null
  surpass_echo "Created passfiles of \"${passname2}\""
} >&2

read_dir "${PASSWORD_STORE_DIR}" '' cmd_bfs

cmd_dfs() {
  if is_dir "${FILE}"; then
    return 0
  fi
  passname="${SUBPATH}"
  surpass_echo "Installing passfiles of \"${passname}\"..."
  message="$(
    surpass_move "${tmpnam}/${passname}" "${passname}" 2>&1
  )" || {
    echo "${message}"
    surpass_ekho "failed to install \"${passname}\""
  }
} >&2

read_dir "${tmpdir}" cmd_dfs

surpass_echo 'All done! Cleaning up...' >&2
